apiVersion: v1
kind: Service
metadata:
  name: webservice
  namespace: test
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32500
  type: NodePort


